# Generated by Django 2.1.2 on 2018-10-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='teamId',
        ),
        migrations.AddField(
            model_name='round',
            name='teamId1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='tabela.Team'),
        ),
        migrations.AddField(
            model_name='round',
            name='teamId2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='tabela.Team'),
        ),
        migrations.AddField(
            model_name='round',
            name='teamWon',
            field=models.IntegerField(null=True),
        ),
    ]
