# Generated by Django 2.1.2 on 2018-10-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0002_auto_20181011_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='teamWon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamWon', to='tabela.Team'),
        ),
    ]
