# Generated by Django 2.1.2 on 2018-10-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0005_auto_20181012_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='teamId1',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='teamId2',
            new_name='team2',
        ),
    ]
